networks:
  nrv.net:
    driver: bridge

services:

  api:
    image: canals/php:latest
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: ./build/Dockerfile
    env_file: ./backend/app/config/token.env
    ports:
      - '42050:80'
    volumes:
      - ./backend/app:/var/php
    working_dir: /var/php
    networks:
      - nrv.net
    depends_on:
      - postgres
    command: php -S 0.0.0.0:80 -t /var/php/public

  postgres:
    image: 'postgres:latest'
    restart: unless-stopped
    env_file: ./backend/app/config/postgres.env
    ports:
      - '42051:5432'
    networks:
      - nrv.net
    volumes:
      - ./app/sql:/var/sql

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - '42052:8080'
    networks:
      - nrv.net
